apiVersion: v2
name: message-service
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "0.1"

dependencies:
  - name: postgresql
    version: 10.13.8
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled